name: Web Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login docker regsitry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}    
    - name: Build the Docker image
      run: docker build . --file web.Dockerfile --tag zlzforever/wildgoose-web
    - name: Publish the Docker image
      run: docker push zlzforever/wildgoose-web      
